import difflib
from typing import List, Tuple, Optional
from .utils import hunk_to_before_after, cleanup_pure_whitespace_lines


class AiderDiffParser:
    """Parses LLM-generated diff blocks into files and hunks."""

    def find_diffs(self, content: str) -> List[Tuple[Optional[str], List[str]]]:
        """Scans for fenced diff blocks and extracts hunks."""
        if not content.endswith("\n"):
            content += "\n"

        lines = content.splitlines(keepends=True)
        edits = []
        line_num = 0
        while line_num < len(lines):
            line = lines[line_num]
            if line.startswith("```diff"):
                line_num, these_edits = self.process_fenced_block(lines, line_num + 1)
                edits += these_edits
            line_num += 1

        # Associate hunks with their paths (paths are inherited within a block)
        final_edits = []
        last_path = None
        for path, hunk in edits:
            if path:
                last_path = path
            else:
                path = last_path
            final_edits.append((path, hunk))

        return final_edits

    def process_fenced_block(self, lines: List[str], start_line_num: int) -> Tuple[int, List[Tuple[Optional[str], List[str]]]]:
        """Extracts hunks from a single fenced diff block."""
        for line_num in range(start_line_num, len(lines)):
            if lines[line_num].startswith("```"):
                break
        
        block = lines[start_line_num:line_num]
        block.append("@@ @@") # Termination sentinel for the parser loop

        fname = None
        if len(block) >= 2 and block[0].startswith("--- ") and block[1].startswith("+++ "):
            b_fname = block[1][4:].strip()
            # Handle git-style b/ prefix
            if b_fname.startswith("b/"):
                fname = b_fname[2:]
            else:
                fname = b_fname
            block = block[2:]

        edits = []
        hunk = []
        has_changes = False
        
        for line in block:
            # Check for mid-block path changes (Aider style)
            if line.startswith("+++ ") and len(hunk) >= 1 and hunk[-1].startswith("--- "):
                # Finish previous hunk (excluding the '--- ' line)
                current_hunk = hunk[:-1]
                if has_changes:
                    edits.append((fname, current_hunk))
                
                # Start new file association
                fname = line[4:].strip()
                hunk = []
                has_changes = False
                continue

            if line.startswith("@@"):
                # Hunk boundary
                if has_changes:
                    edits.append((fname, hunk))
                hunk = []
                has_changes = False
                continue

            hunk.append(line)
            if line.startswith(("-", "+")):
                has_changes = True

        return line_num + 1, edits

    def normalize_hunk(self, hunk: List[str]) -> List[str]:
        """Re-renders hunk using difflib for canonical consistency."""
        before, after = hunk_to_before_after(hunk, lines=True)
        
        before = cleanup_pure_whitespace_lines(before)
        after = cleanup_pure_whitespace_lines(after)

        # Generate a clean unified diff from the extracted parts
        # n=max(len(before), len(after)) ensures we get all context
        diff = difflib.unified_diff(before, after, n=max(len(before), len(after)))
        
        # Skip the ---, +++, and @@ headers generated by difflib
        diff_lines = list(diff)[3:]
        return diff_lines
