from __future__ import annotations

import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from agentd.domain.models import TaskRecord


DEFAULT_IGNORE_PATTERNS: tuple[str, ...] = (
    ".git",
    ".agentd",
    ".ai-editor",
    ".tmp",
    "node_modules",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    "target",
    "dist",
)


@dataclass(frozen=True)
class ShadowWorkspace:
    task_id: str
    real_path: Path
    shadow_path: Path


class ShadowWorkspaceManager:
    def __init__(
        self,
        root_path: Path | None = None,
        ignore_patterns: Sequence[str] | None = None,
        checkpoint_retention_tasks: int = 20,
    ) -> None:
        self._root_path = (root_path or Path(tempfile.gettempdir()) / "ai-editor-shadow").resolve()
        self._ignore_patterns = tuple(ignore_patterns or DEFAULT_IGNORE_PATTERNS)
        self._checkpoint_retention_tasks = max(1, checkpoint_retention_tasks)
        self._root_path.mkdir(parents=True, exist_ok=True)

    async def prepare(self, task_id: str, workspace_path: str) -> ShadowWorkspace:
        real_path = Path(workspace_path).resolve()
        if not real_path.exists() or not real_path.is_dir():
            msg = f"Workspace path is not a directory: {workspace_path}"
            raise RuntimeError(msg)

        shadow_path = self._resolve_shadow_path(task_id)
        if shadow_path.exists():
            shutil.rmtree(shadow_path)

        shutil.copytree(
            real_path,
            shadow_path,
            ignore=shutil.ignore_patterns(*self._ignore_patterns),
        )

        return ShadowWorkspace(
            task_id=task_id,
            real_path=real_path,
            shadow_path=shadow_path,
        )

    async def prepare_lightweight(
        self,
        task_id: str,
        workspace_path: str,
        target_files: list[str],
    ) -> ShadowWorkspace:
        """Create a shadow that contains only the listed target files.

        Copies each file in target_files (relative paths) from workspace_path
        into the shadow, preserving directory structure.  Any parent directories
        are created as needed.  Only the files required for the inline change are
        present — no full workspace copy.
        """
        real_path = Path(workspace_path).resolve()
        if not real_path.exists() or not real_path.is_dir():
            msg = f"Workspace path is not a directory: {workspace_path}"
            raise RuntimeError(msg)

        shadow_path = self._resolve_shadow_path(task_id)
        if shadow_path.exists():
            shutil.rmtree(shadow_path)
        shadow_path.mkdir(parents=True, exist_ok=True)

        for rel in target_files:
            src = self._resolve_inside(real_path, rel)
            dst = self._resolve_inside(shadow_path, rel)
            if src.exists():
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)

        return ShadowWorkspace(
            task_id=task_id,
            real_path=real_path,
            shadow_path=shadow_path,
        )

    async def clone(
        self,
        parent_task_id: str,
        child_task_id: str,
        workspace_path: str,
        *,
        src_override: Path | None = None,
    ) -> ShadowWorkspace:
        """Copy the parent's shadow workspace into a new path for a child task.

        src_override: use this path as source instead of deriving from parent_task_id.
        Pass when the stored shadow_workspace_path differs from the generated path (e.g.
        after a cross-task shadow redirect caused by a backend restart).
        """
        src = src_override or self._resolve_shadow_path(parent_task_id)
        if not src.exists():
            raise RuntimeError(f"Parent shadow workspace does not exist: {src}")
        dst = self._resolve_shadow_path(child_task_id)
        if dst.exists():
            shutil.rmtree(dst)
        # Apply the same ignore patterns as prepare(): the parent shadow accumulates
        # tooling caches (.mypy_cache, .pytest_cache, __pycache__, …) generated by
        # validation runs. Copying them into the child would bloat it and, worse, let
        # mypy/ruff/pytest reuse STALE ancestor results or bytecode across the resume chain.
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns(*self._ignore_patterns))
        return ShadowWorkspace(
            task_id=child_task_id,
            real_path=Path(workspace_path).resolve(),
            shadow_path=dst,
        )

    async def promote(self, task: TaskRecord) -> None:
        if task.shadow_workspace_path is None:
            msg = f"Task {task.task_id} has no shadow workspace"
            raise RuntimeError(msg)

        real_path = Path(task.workspace_path).resolve()
        shadow_path = Path(task.shadow_workspace_path).resolve()

        for relative_path in sorted(set(task.modified_files)):
            source = self._resolve_inside(shadow_path, relative_path)
            destination = self._resolve_inside(real_path, relative_path)

            if source.exists():
                destination.parent.mkdir(parents=True, exist_ok=True)
                if source.is_dir():
                    if destination.exists():
                        shutil.rmtree(destination)
                    shutil.copytree(source, destination)
                else:
                    shutil.copy2(source, destination)
                continue

            if destination.is_file():
                destination.unlink()
            elif destination.is_dir():
                shutil.rmtree(destination)

    async def cleanup(self, task: TaskRecord) -> None:
        if task.shadow_workspace_path is None:
            return

        shadow_path = Path(task.shadow_workspace_path).resolve()
        if shadow_path.exists():
            shutil.rmtree(shadow_path)

    async def prune_checkpoints(self) -> None:
        checkpoints_root = self._root_path / "_checkpoints"
        if not checkpoints_root.exists() or not checkpoints_root.is_dir():
            return

        task_dirs = [path for path in checkpoints_root.iterdir() if path.is_dir()]
        task_dirs.sort(key=lambda item: item.stat().st_mtime, reverse=True)

        for stale_dir in task_dirs[self._checkpoint_retention_tasks :]:
            shutil.rmtree(stale_dir, ignore_errors=True)

    def _resolve_shadow_path(self, task_id: str) -> Path:
        shadow_path = (self._root_path / task_id).resolve()
        try:
            shadow_path.relative_to(self._root_path)
        except ValueError as exc:
            msg = f"Unsafe task id for shadow workspace path: {task_id}"
            raise RuntimeError(msg) from exc
        return shadow_path

    def _resolve_inside(self, root: Path, relative_path: str) -> Path:
        candidate = (root / relative_path).resolve()
        try:
            candidate.relative_to(root)
        except ValueError as exc:
            msg = f"Path escapes workspace: {relative_path}"
            raise RuntimeError(msg) from exc
        return candidate
